version: '3'
services:
  magic:
    image: trunghadev/grocery-crawler:latest
    command: mage start oz-grocery-price-analysis
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/oz-grocery-price-analysis
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5

