triggers:
- envs: []
  last_enabled_at: 2024-03-17 03:13:26.304194
  name: Daily Run @ 1am
  pipeline_uuid: category_crawler_woolies
  schedule_interval: 0 14 * * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-17 03:13:00
  status: active
  variables: {}
