triggers:
- envs: []
  last_enabled_at: 2024-04-25 11:37:57.158576
  name: Daily Run @ 1am
  pipeline_uuid: woolies_end_to_end_crawler
  schedule_interval: 0 15 * * *
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-18 08:22:00
  status: active
  variables: {}
