triggers:
- envs: []
  last_enabled_at: 2024-03-17 00:39:50.933589
  name: Run Once
  pipeline_uuid: category_crawler_coles
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-03-17 00:39:00
  status: inactive
  variables: {}
